### ISSUE TITLE
Send out customised emails to a mailing list

### ISSUE THREAD

**Issue by lewistaylor** [dangerfarms/csvmail#1]
As a User
I want to send out customised emails to a mailing list
So that I don't have to manually send them one after the other

**Description**

**UI / Design**
Make use of the django-rest-framework's built in web interface.

**Tasks**
- [ ] Create Backend API

**Acceptance Criteria**
- [ ] As an anonymous user, if i try to send mail, then my request is unauthorized
- [ ] As an authenticated user, if i send mail to a list of users, the users receive my messages
- [ ]
